---
- name: Install nginx
  apt: 
    name: nginx 
    state: present

- name: Create ssl certificates
  include_tasks: ssl.yml

- name: Remove all configured websites
  shell: |
    rm -rf /etc/nginx/sites-available/*

- name: Copy nginx configuration for wordpress
  template: 
    src: wordpress.conf.j2 
    dest: /etc/nginx/sites-available/wordpress.conf
  notify: restart nginx