- name: Create RDS instance
  rds:
    command: create
    instance_name: wordpress-db
    db_engine: MySQL
    size: '20'
    instance_type: db.t2.micro
    username: "{{ mysql_user }}"
    password: "{{ mysql_pswd }}"
    security_groups: "{{ group_id }}"
    region: "{{ aws_region }}"
    tags:
      Environment: testing
      Application: cms
    wait: yes
    wait_timeout: 600
  register: rds